version: '3.8'

services:
  consumer-server:
    build:
      context: .
      dockerfile: ./packages/consumer-server/Dockerfile
    ports:
      - "3002:3002"
    environment:
      # Server
      - PORT=3002
      - NODE_ENV=production

      # BigQuery - Paste the entire JSON content of your service account key
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}

      # Email - Brevo SMTP
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - NOTIFICATION_EMAILS=${NOTIFICATION_EMAILS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
